server:
  port: 80
spring:
  application:
    name: rabbitmq-delay
  rabbitmq:
    host: localhost # default localhost
    port: 5672 # default 5672
    username: guest # default guest
    password: guest # default guest
    publisher-returns: true  #开启发送失败回退
    #开启ack
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual #采取手动应答
        #concurrency: 1 # 指定最小的消费者数量
        #max-concurrency: 1 #指定最大的消费者数量
        retry:
          enabled: true # 是否支持重试
